general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 12

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.85

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
